# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Express - Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/apps/services/**"
      - ".github/workflows/main_express-microservice.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: yarn install and build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            src/yarn.lock
            src/package-lock.json
      - run: |
          yarn
          yarn nx run services:build --configuration=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            src/dist/apps/services
            src/package.json
            src/scripts
            src/scripts/requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - run: mv dist/apps/services/* .

      - run: yarn --production

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "express-microservice"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B5AD89411527464CA08BE8E4F87274B2 }}
          package: .

  install-dependencies:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.10"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r src/scripts/requirements.txt
